name: Wails build

on:
  push:
    tags:
    # Match any new tag
      - '*-release'
      - '*-dev'

env:
  # Necessary for most environments as build failure can occur due to OOM issues
  NODE_OPTIONS: "--max-old-space-size=4096"
  OFFICIAL_STATEMENT: ${{ vars.OFFICIAL_STATEMENT }}

jobs:
  build:
    strategy:
    # Failure in one platform build won't impact the others
      fail-fast: false
      matrix:
        build:
          - name: 'go-stock-windows-amd64.exe'
            platform:  'windows/amd64'
            os: 'windows-latest'
#          - name: 'go-stock-linux-amd64'
#            platform: 'linux/amd64'
#            os: 'ubuntu-latest'
          - name: 'go-stock-darwin-universal'
            platform: 'darwin/universal'
            os: 'macos-latest'

    runs-on: ${{ matrix.build.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Get commit message
        id: get_commit_message
        run: |
          $commit_message = & git log -1 --pretty=format:"%s"
          echo "::set-output name=commit_message::$commit_message"

      - name: Build wails x go-stock
        uses: ArvinLovegood/wails-build-action@v3.6
        id: build
        with:
          build-name: ${{ matrix.build.name }}
          build-platform: ${{ matrix.build.platform }}
          package: true
          go-version: '1.24'
          build-tags: ${{ github.ref_name }}
          build-commit-message: ${{ steps.get_commit_message.outputs.commit_message }}
          build-statement: ${{ env.OFFICIAL_STATEMENT }}
          node-version: '20.x'
